version: "3.9"
services:
  db:
    image: mongo:latest
    container_name: mongodb-task-manager-container
    environment:
      MONGO_INITDB_DATABASE: task-manager
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  api:
    image: api-task-manager
    container_name: api-task-manager-container
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: ./config/.env
    command: npm run prod
    restart: always
    ports:
      - ${PORT}:5000
    volumes:
      - ./dist:/usr/src/api-task-manager/dist
    depends_on:
      - db
    links:
      - db